// ForgeGradle 2.1 is the toolchain for 1.8.9. Needs JDK 8 and Gradle 4.x.
buildscript {
    repositories {
        mavenCentral()
        maven { name = 'forge'; url = 'https://maven.minecraftforge.net/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = project.mod_version
group = 'weirdGUI'
archivesBaseName = 'weirdGUI'

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
    options.encoding = 'UTF-8'
}

minecraft {
    version = project.forge_version
    runDir = 'run'
    mappings = project.mappings_version
    makeObfSourceJar = false
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft.version

    // keep mcmod.info's version in sync with gradle.properties
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.mc_version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes 'FMLCorePluginContainsFMLMod': 'true'
    }
}
